name: Deploy to Render

on:
  push:
    branches: [main] # Or your default deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred LTS version like 18.x or 20.x

      - name: Install dependencies
        run: npm ci # 'npm ci' is generally preferred for CI for consistent installs

      - name: Run Prisma Generate
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Needed for Prisma generate if it connects

      - name: Build application
        run: npm run build

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: success() && secrets.RENDER_DEPLOY_HOOK != '' 